name: nexrad
description: Dart decoder for nexrad radar data.
version: 0.0.1
homepage: https://www.neis.es
author: Alex Neises <alex@neis.es>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  intl: ^0.15.0
  bzip2: ^0.0.6
  markdown: ^0.9.0

dev_dependencies:
  test: ^0.12.0
